### ISSUE TITLE
Validators broken since ivy

### ISSUE THREAD

**Issue by shprink** [rsaenen/ngx-custom-validators#38] opened 2020-05-22 09:53 UTC
Hello,

I have upgraded Angular and your lib to v9 and now the equalTo validator breaks the app.

Here is the example with and without Ionic: https://stackblitz.com/edit/angular-ivy-ipk5rp

remove `[equalTo]` and it will work

**Comment by bjornharvold** [comment] 2020-05-23 02:15
Duplicate of #33

**Comment by suhailkc** [comment] 2020-08-06 08:22
@shprink 
I have the same issue using equalTo and notEqualTo validators.

```
<input class="form-control" type="text" placeholder="password" ngModel name="password" #password="ngModel"/>
<input class="form-control mt-2" type="text" placeholder="re-enter password" ngModel name="equalToPassword" #equalToPassword="ngModel" [equalTo]="password"/>

<p *ngIf="equalToPassword?.errors?.equalTo">equalTo error</p>
```


Error when `ng build --prod` :

`Type 'NgModel' is missing the following properties from type 'FormControl': setValue, patchValue, registerOnChange, registerOnDisabledChange, and 28 more.`


Versions:
Angular: 10.0.7
ngx-custom-validators: ^8.0.0 (downgraded from ^9.1.0 because of error in Angular 10)


Could anybody know the solution?

**Closed** 2020-10-14 15:23 UTC
